Write-Output "                      ___====-_  _-====___"
Write-Output "                _--^^^#####//      \#####^^^--_"
Write-Output "             _-^##########// (    ) \##########^-_"
Write-Output "            -############//  |\^^/|  \############-"
Write-Output "          _/############//   (@::@)   \############\_"
Write-Output "         /#############((     \\//     ))#############\"
Write-Output "        -###############\\    (oo)    //###############-"
Write-Output "       -#################\\  / '' \  //#################-"
Write-Output "      -###################\\/  ||  \/###################-"
Write-Output "     _#/|##########/\######(   ''   )######/\##########|\#_"
Write-Output "    |/ |#/\#/\#/\/  \#/\##\         /##/\#/\#\/  \#/\#| \|"
Write-Output "        |/  V  ()     V  |         |  V    ()    V  |/   "
Write-Output "                _//       \\       //      \\_"
Write-Output "           __.-'           )     (          `-.__"
Write-Output "          (__.-----..____..-'     `-..____..-----.__)"
Write-Output ""
Write-Output "                   *** DRAGON ***"
Write-Output "         Beware! The ASCII dragon is here!"
